import { Footer, Nav, ReduxProvider } from "@/components";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const manrope = localFont({
	src: "../../public/fonts/Manrope-VariableFont_wght.ttf",
	variable: "--font-manrope",
	display: "swap",
});

const open_sans = localFont({
	src: "../../public/fonts/OpenSans-VariableFont_wdth,wght.ttf",
	variable: "--font-open-sans",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Boldo | Home",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${manrope.variable} ${open_sans.variable} dark:bg-custom-dark-blue`}>
				<ReduxProvider>
					<Nav />
					{children}
					<Footer />
				</ReduxProvider>
			</body>
		</html>
	);
}
